// export const GET_EVENTS = "GET_EVENTS";
// export const GET_EVENTS_CALL = 'GET_EVENTS_CALL';
// export const EVENTS_LOADER = 'EVENTS_LOADER';
// export const POST_EVENT = 'POST_EVENT';
// export const DELETE_EVENT = 'DELETE_EVENT';
// export const UPDATE_EVENT = 'UPDATE_EVENT';
// export const SET_CURRENT_ID = 'SET_CURRENT_ID';
// export const AUTH = "AUTH";
// export const CALL_AUTH = 'CALL_AUTH';
// export const LOG_OUT = 'LOG_OUT';
// export const LOG_OUT_USER = 'LOG_OUT_USER';
// export const POST_EVENT_ACTION = 'POST_EVENT_ACTION';
// export const DELETE_EVENT_ACTION = 'DELETE_EVENT_ACTION';
// export const UPDATE_EVENT_ACTION = 'UPDATE_EVENT_ACTION';

// export default {
//     GET_EVENTS : "GET_EVENTS",
//     GET_EVENTS_CALL : 'GET_EVENTS_CALL',
//     EVENTS_LOADER : 'EVENTS_LOADER',
//     POST_EVENT : 'POST_EVENT',
//     DELETE_EVENT : 'DELETE_EVENT',
//     UPDATE_EVENT : 'UPDATE_EVENT',
//     SET_CURRENT_ID : 'SET_CURRENT_ID',
//     AUTH : "AUTH",
//     CALL_AUTH : 'CALL_AUTH',
//     LOG_OUT : 'LOG_OUT',
//     LOG_OUT_USER : 'LOG_OUT_USER',
//     POST_EVENT_ACTION : 'POST_EVENT_ACTION',
//     DELETE_EVENT_ACTION : 'DELETE_EVENT_ACTION',
//     UPDATE_EVENT_ACTION : 'UPDATE_EVENT_ACTION',
//     TAKE_CURRENT_ID: 'TAKE_CURRENT_ID'
// };

export const 
    GET_EVENTS = "GET_EVENTS",
    GET_EVENTS_CALL = 'GET_EVENTS_CALL',
    EVENTS_LOADER = 'EVENTS_LOADER',
    POST_EVENT = 'POST_EVENT',
    DELETE_EVENT = 'DELETE_EVENT',
    UPDATE_EVENT = 'UPDATE_EVENT',
    SET_CURRENT_ID = 'SET_CURRENT_ID',
    AUTH = "AUTH",
    CALL_AUTH = 'CALL_AUTH',
    LOG_OUT = 'LOG_OUT',
    LOG_OUT_USER = 'LOG_OUT_USER',
    POST_EVENT_ACTION = 'POST_EVENT_ACTION',
    DELETE_EVENT_ACTION = 'DELETE_EVENT_ACTION',
    UPDATE_EVENT_ACTION = 'UPDATE_EVENT_ACTION',
    TAKE_CURRENT_ID= 'TAKE_CURRENT_ID',
    CALL_UPDATE_EVENT = 'CALL_UPDATE_EVENT',
    CALL_DELETE_EVENT = 'CALL_DELETE_EVENT',
    CALL_LIKE_EVENT = 'CALL_LIKE_EVENT',
    CALL_SIGNUP = 'CALL_SIGNUP'

